version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
      - test-db

  frontend-dev:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: >
      bash -c "cd /app &&
               npm install &&
               npm run start -- --host 0.0.0.0 --disable-host-check --poll=2000"
    environment:
      - NODE_ENV=development
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  test-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    volumes:
      - ./backend/database/test_init.sql:/docker-entrypoint-initdb.d/test_init.sql
      - mysql_test_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
  mysql_test_data:
